[package]
name = "tinywasm-root"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[workspace]
resolver = "3"
members = ["crates/*"]
default-members = [".", "crates/parser", "crates/tinywasm", "crates/types"]

[workspace.package]
version = "0.11.0-pre.0"
edition = "2024"
rust-version = "1.95"
repository = "https://github.com/explodingcamera/tinywasm"
license = "MIT OR Apache-2.0"
keywords = ["interpreter", "no-std", "tinywasm", "wasm", "webassembly"]
categories = ["compilers", "embedded", "no-std", "virtualization", "wasm"]

[workspace.dependencies]
tinywasm = { path = "crates/tinywasm", version = "0.11.0-pre.0", default-features = false }
tinywasm-parser = { path = "crates/parser", version = "0.11.0-pre.0", default-features = false }
tinywasm-types = { path = "crates/types", version = "0.11.0-pre.0", default-features = false }

anyhow = "1.0"
log = "0.4"
owo-colors = { version = "4.3" }
pretty_env_logger = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
wasm-testsuite = { version = "0.7" }
wasmparser = { version = "0.255", default-features = false }
wast = "255"
wat = "1.255"

criterion = { version = "0.8", default-features = false, features = [
  "cargo_bench_support",
  "rayon"
] }

[[example]]
name = "wasm-rust"
test = false

[[bench]]
harness = false
name = "argon2id"

[[bench]]
harness = false
name = "fibonacci"

[[bench]]
harness = false
name = "tinywasm"

[[bench]]
harness = false
name = "tinywasm_modes"

[[bench]]
harness = false
name = "memory_backends"

[dev-dependencies]
anyhow.workspace = true
criterion.workspace = true
pretty_env_logger.workspace = true
tinywasm = { path = "crates/tinywasm" }
tinywasm-parser.workspace = true
wat.workspace = true

[profile.bench]
opt-level = 3
debug = true
lto = "thin"
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = true

[profile.samply]
inherits = "release"
debug = true

[profile.wasm]
inherits = "release"
opt-level = 3
lto = "thin"
panic = "abort"
codegen-units = 1
