[package]
name = "tinywasm-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Minimal command-line interface for TinyWasm"
documentation = "https://docs.rs/tinywasm-cli"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["cli", "runtime", "tinywasm", "wasm", "webassembly"]
categories = ["command-line-utilities", "wasm"]

[lib]
name = "tinywasm_cli"
path = "src/lib.rs"

[[bin]]
name = "tinywasm"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstream = { version = "1.0" }
anyhow.workspace = true
clap = { version = "4.6", features = ["derive"] }
clap_complete = "4.6"
log.workspace = true
owo-colors = { workspace = true }
pretty_env_logger.workspace = true
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
tinywasm = { workspace = true, features = [
  "archive",
  "canonicalize-nans",
  "debug",
  "guest-debug",
  "log",
  "parallel-parser",
  "parser",
  "std",
  "validate",
] }
wasm-testsuite = { workspace = true, optional = true }
wast = { workspace = true, optional = true }
wat = { workspace = true, optional = true }

[dev-dependencies]
assert_cmd = "2.2"
predicates = "3.1"
tempfile = "3.27"

[features]
default = ["wast", "wat"]
tests = ["dep:serde", "dep:serde_json", "dep:wasm-testsuite", "wast"]
wast = ["dep:wast"]
wat = ["dep:wat"]
