[package]
name = "bench-guest"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[[bin]]
name = "argon2id"
path = "src/argon2id.rs"

[[bin]]
name = "compression"
path = "src/compression.rs"

[[bin]]
name = "json"
path = "src/json.rs"

[[bin]]
name = "nested"
path = "src/nested.rs"

[dependencies]
argon2 = { version = "0.6", default-features = false, features = ["alloc"] }
miniz_oxide = "0.9"
serde_json = "1.0"
tinywasm = { path = "../../tinywasm", default-features = false, features = ["parser", "std"] }

[profile.release]
opt-level = 3
strip = true
lto = "thin"
codegen-units = 1
