[package]
name = "tinywasm-parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Parser and lowering pipeline for TinyWasm"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
log = { workspace = true, optional = true }
tinywasm-types = { workspace = true }
wasmparser = { workspace = true, features = ["features", "simd", "validate"] }

[features]
default = ["log", "parallel", "std"]
log = ["dep:log"]
parallel = ["std"]
std = ["tinywasm-types/std", "wasmparser/std"]
