(module
  (func (export "i32-add-locals-across-loop-boundary") (param i32) (result i32)
    (block (result i32)
      (local.get 0)
      (loop (param i32) (result i32)
        (local.get 0)
        (i32.add)
        (br 1)
      )
    )
  )

  (func (export "i64-add-locals-across-loop-boundary") (param i64) (result i64)
    (block (result i64)
      (local.get 0)
      (loop (param i64) (result i64)
        (local.get 0)
        (i64.add)
        (br 1)
      )
    )
  )
)

(assert_return (invoke "i32-add-locals-across-loop-boundary" (i32.const 7)) (i32.const 14))
(assert_return (invoke "i64-add-locals-across-loop-boundary" (i64.const 9)) (i64.const 18))
