(module
  (type $result (func (result i32)))
  (func $seven (type $result) (i32.const 7))
  (func $nine (type $result) (i32.const 9))

  (table $table 3 5 funcref)
  (elem (table $table) (i32.const 1) func $seven)
  (elem $passive func $nine)

  (func (export "size") (result i32)
    (table.size $table))
  (func (export "is-null") (param $index i32) (result i32)
    (ref.is_null (table.get $table (local.get $index))))
  (func (export "call") (param $index i32) (result i32)
    (call_indirect $table (type $result) (local.get $index)))
  (func (export "set-nine") (param $index i32)
    (table.set $table (local.get $index) (ref.func $nine)))
  (func (export "init-nine") (param $index i32)
    (table.init $table $passive (local.get $index) (i32.const 0) (i32.const 1)))
)

(assert_return (invoke "size") (i32.const 3))
(assert_return (invoke "is-null" (i32.const 0)) (i32.const 1))
(assert_return (invoke "is-null" (i32.const 1)) (i32.const 0))
(assert_return (invoke "call" (i32.const 1)) (i32.const 7))
(assert_return (invoke "set-nine" (i32.const 0)))
(assert_return (invoke "is-null" (i32.const 0)) (i32.const 0))
(assert_return (invoke "call" (i32.const 0)) (i32.const 9))
(assert_return (invoke "is-null" (i32.const 2)) (i32.const 1))
(assert_return (invoke "init-nine" (i32.const 2)))
(assert_return (invoke "is-null" (i32.const 2)) (i32.const 0))
(assert_return (invoke "call" (i32.const 2)) (i32.const 9))
