;; Focused table64 execution and mixed-width operand coverage.
(module
  (type $result (func (result i32)))
  (func $seven (type $result) (i32.const 7))
  (func $nine (type $result) (i32.const 9))

  (table $t64 i64 4 8 funcref)
  (table $other64 i64 4 funcref)
  (table $t32 4 funcref)
  (elem (table $t64) (i64.const 1) func $seven)
  (elem $passive func $nine)

  (func (export "size64") (result i64)
    (table.size $t64))
  (func (export "grow64") (result i64)
    (table.grow $t64 (ref.null func) (i64.const 2)))
  (func (export "call-active") (result i32)
    (call_indirect $t64 (type $result) (i64.const 1)))
  (func (export "set-and-call") (result i32)
    (table.set $t64 (i64.const 0) (ref.func $nine))
    (call_indirect $t64 (type $result) (i64.const 0)))
  (func (export "init-and-call") (result i32)
    (table.init $t64 $passive (i64.const 2) (i32.const 0) (i32.const 1))
    (call_indirect $t64 (type $result) (i64.const 2)))
  (func (export "copy64-and-call") (result i32)
    (table.copy $other64 $t64 (i64.const 0) (i64.const 1) (i64.const 1))
    (call_indirect $other64 (type $result) (i64.const 0)))
  (func (export "copy-to-32-and-call") (result i32)
    (table.copy $t32 $t64 (i32.const 0) (i64.const 1) (i32.const 1))
    (call_indirect $t32 (type $result) (i32.const 0)))
  (func (export "copy-to-64-and-call") (result i32)
    (table.copy $other64 $t32 (i64.const 1) (i32.const 0) (i32.const 1))
    (call_indirect $other64 (type $result) (i64.const 1)))
  (func (export "fill64")
    (table.fill $t64 (i64.const 1) (ref.null func) (i64.const 1)))
  (func (export "get-oob") (result funcref)
    (table.get $t64 (i64.const -1)))
)

(assert_return (invoke "size64") (i64.const 4))
(assert_return (invoke "call-active") (i32.const 7))
(assert_return (invoke "set-and-call") (i32.const 9))
(assert_return (invoke "init-and-call") (i32.const 9))
(assert_return (invoke "copy64-and-call") (i32.const 7))
(assert_return (invoke "copy-to-32-and-call") (i32.const 7))
(assert_return (invoke "copy-to-64-and-call") (i32.const 7))
(assert_return (invoke "grow64") (i64.const 4))
(assert_return (invoke "size64") (i64.const 6))
(assert_return (invoke "fill64"))
(assert_trap (invoke "call-active") "uninitialized element")
(assert_trap (invoke "get-oob") "out of bounds table access")
